#!/bin/bash

mkdir md
cd md

#wget https://files.rcsb.org/download/1RDC.pdb
wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/1RDC.pdb
grep -v HOH 1RDC.pdb > 1RDC_clean.pdb
gmx pdb2gmx -f 1RDC_clean.pdb -o 1RDC_processed.gro -water spce <<< "15"

gmx editconf -f 1RDC_processed.gro -o 1RDC_newbox.gro -c -d 1.0 -bt cubic
gmx solvate -cp 1RDC_newbox.gro -cs spc216.gro -o 1RDC_solv.gro -p topol.top

wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/ions.mdp
gmx grompp -f ions.mdp -c 1RDC_solv.gro -p topol.top -o ions.tpr
gmx genion -s ions.tpr -o 1RDC_solv_ions.gro -p topol.top -pname NA -nname CL -neutral <<< "13"

wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/minim.mdp
gmx grompp -f minim.mdp -c 1RDC_solv_ions.gro -p topol.top -o em.tpr
gmx mdrun -v -deffnm em
gmx energy -f em.edr -o potential.xvg <<< "10"

wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/nvt.mdp
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
gmx mdrun -deffnm nvt
gmx energy -f nvt.edr -o temperature.xvg <<< "16"

wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/npt.mdp
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx mdrun -deffnm npt
gmx energy -f npt.edr -o pressure.xvg <<< "18"

wget https://raw.githubusercontent.com/Sanches-wolf228/Bioinformatics-4/main/source/md.mdp
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md_0_1.tpr
gmx mdrun -deffnm md_0_1

echo -e "1\n0" | gmx trjconv -s md_0_1.tpr -f md_0_1.xtc -o md_0_1_noPBC.xtc -pbc mol -center
echo -e "4\n4" | gmx rms -s md_0_1.tpr -f md_0_1_noPBC.xtc -o rmsd.xvg -tu ns

gmx gyrate -s md_0_1.tpr -f md_0_1_noPBC.xtc -o gyrate.xvg <<< "1"